from coordinate import Coordinate
from image import Image

DEFAULT_TITLE = 'no title'

DEFAULT_IMAGE = 'default.bmp'

DEFAULT_SCREEN_WIDTH = 800
DEFAULT_SCREEN_HEIGHT = 600
DEFAULT_SCREEN_SIZE = (DEFAULT_SCREEN_WIDTH, DEFAULT_SCREEN_HEIGHT)

DEFAULT_FPS = 60

DEFAULT_IMAGE = Image()
DEFAULT_POSITION = Coordinate(0, 0)
DEFAULT_DIRECTION = 0
