UNIT_MAX_SPEED = 3
UNIT_MAX_ROLL_ANGLE = 0.05


UNIT_TIME_NEXT_FIRING = 5
UNIT_DEFAULT_HP = 30
UNIT_DEFAULT_ATTACK_POWER = 5

BASE_DEFAULT_HP = 600
BASE_DEFAULT_RECOVER_INTERVAL = 30

BULLET_SPEED = 20
BULLET_RANGE = 600

FIELD_CELL_WIDTH = 40
FIELD_CELL_HEIGHT = 40


RADIUS_OF_THE_UNIT = 16
RADIUS_OF_THE_BASE = 20
RADIUS_OF_THE_ITEM = 20
PUSH_STRENGTH = 0.5
RADIUS_OF_THE_VISILITY_ARIA = 400


ITEM_RESURRECTION_INTERVAL = 300
ITEM_HP_INCREASE_AMOUNT = 15
ITEM_ATTACK_INCREASE_AMOUNT = 1
